---
title: "Project 1 Checkpoint 3"
format: html
embed-resources: true
editor: source
execute: 
  echo: true
  error: true
---



```{r}
#| label: packages-setup
#| message: false
#| warning: false

library(httr)
library(tidyjson)
library(jsonlite)
library(tidyverse)
library(glue)
```


```{r}
country = "CAN"
baseurl = "https://api.api-ninjas.com/v1/unemployment?country="
can_url = glue("{baseurl}{country};X-Api-Key={key}")

can_data = fromJSON(can_url)
```

```{r}
funky_Employ <- function(country_code){
  baseurl = "https://api.api-ninjas.com/v1/unemployment?country="
  url = glue("{baseurl}{country_code};X-Api-Key={key}")
  employ_data = fromJSON(url)
  return(employ_data)
}
can_data <- funky_Employ(country)
```

```{r}
democracy_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-11-05/democracy_data.csv')
democ_countrycode <- democracy_data |>
  select(country_code) |>
  distinct(country_code) |>
  pull(country_code)
```

```{r}
employ <- map(democ_countrycode, funky_Employ)
#employ2 <- map_dfr(democ_countrycode, funky_Employ)
write.csv(employ2, "employ2.csv", row.names = FALSE)
employ <- read.csv("employ2.csv")
#4543 rows
employ |> 
  distinct(country_code) |>
  count()
#110 countries in this 

names(employ) <- c("country_code", "year", "unemployment_rate")

#check for duplicate countries & years
democracy_data |>
  count(country_code, year) |>
  filter(n > 1)

employ |>
  add_count(country_code, year) |>
  filter(n > 1)
#shows that there are 40 country code duplicates
employ<- employ |>
  distinct()

employ_democracy_data <- democracy_data |>
  left_join(employ, by = c("country_code", "year"))

employ_democracy_data |>
  summarize(missing_unemployment = sum(is.na(unemployment_rate)))
#11195 missing values which makes sense because this api only has data for 110 countries and limited years

write.csv(employ_democracy_data, "employ_democracy_data.csv", row.names = FALSE)
```

